---


- name: copy sh
  template: 
    src: "templates/backup.sh.j2"
    dest: "/home/app/bakcup.sh"
    owner: root
    group: root
    mode: 0700

- name: cron db backup
  cron:
    name: "redis backup" 
    minute: "0" 
    hour: "*" 
    day: "*" 
    job: "/bin/bash /home/app/backup.sh"