---

- name: install nginx
  yum:
    name: "nginx"
    state: present

- name: copy nginx config file
  template: 
    src: "templates/nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    owner: "nginx"
    group: "nginx"
    mode: 0640