---

- name: start nginx
  systemd:
    name: nginx
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: start redis
  systemd:
    name: redis
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: start app
  systemd:
    name: app
    daemon_reload: yes
    state: restarted
    enabled: yes