apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv1
  labels:
    type: local
    name: redis-demo
spec:
  capacity:
    storage: 1Gi 
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/redis/data
